services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - sprite-server
    environment:
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - poke-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ingest:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - POKEAPI_CSV_DIR=${POKEAPI_CSV_DIR}
      - SPRITE_DIR=/data/sprites
    volumes:
      - ./ingest/csv:${POKEAPI_CSV_DIR}
      - poke-sprites:/data/sprites

  sprite-server:
    image: nginx:alpine
    volumes:
      - poke-sprites:/usr/share/nginx/html:ro
    ports:
      - "8090:80"

volumes:
  poke-data:
  poke-sprites:
